### ISSUE TITLE
v2.0.0与v2.1.1 curl http://127.0.0.1/test/hub?getServiceStat 无响应或者500报错 

### ISSUE THREAD

**Issue by stone-wind** [aimingoo/ngx_cc#1]
您好， 我是lua初学者，正在学习您的ngx_cc 。
我使用的是nginx-1.9.9+LuaJIT-2.1-20151219 +ngx_lua-0.9.20 测试的（patch文件匹配有修正，具体增加无改动），使用release 版本v2.0.0与v2.1.1时， curl http://127.0.0.1/test/hub?getServiceStat 无响应或者500报错 。针对v2.0.0，报错如下：
                2016/01/12 08:41:07 [error] 50188#0: *19 lua entry thread aborted: runtime error: /usr/local/nginx/ngx_cc-2.0.0/lib/JSON.lua:398: JSON:encode must be called in method format
stack traceback:
coroutine 0:
        [C]: in function 'assert'
        /usr/local/nginx/ngx_cc-2.0.0/lib/JSON.lua:398: in function 'onEncodeError'
        /usr/local/nginx/ngx_cc-2.0.0/lib/JSON.lua:940: in function 'encode'
        /usr/local/nginx/ngx_cc-2.0.0/module/invoke.lua:29: in function 'invoker'
        /usr/local/nginx/ngx_cc-2.0.0/ngx_cc.lua:454: in function 'invokes'
        content_by_lua(nginx.conf:67):1: in function <content_by_lua(nginx.conf:67):1>, client: 127.0.0.1, server: localhost, request: "GET /test/hub?getServiceStat HTTP/1.0", host: "127.0.0.1:8011"
    我通过把invoke.lua:29的JSON.encode 改成JSON:encode,curl http://127.0.0.1/test/hub?getServiceStat 有正确响应。
   针对v2.1.1，报错如下：
    2016/01/12 08:47:35 [error] 50557#0: *15 lua entry thread aborted: runtime error: /usr/local/nginx/ngx_cc-2.1.1/ngx_cc.lua:496: bad argument #1 to 'gmatch' (string expected, got nil)
stack traceback:
coroutine 0:
        [C]: in function 'gmatch'
        /usr/local/nginx/ngx_cc-2.1.1/ngx_cc.lua:496: in function '__index'
        /usr/local/nginx/ngx_cc-2.1.1/ngx_cc.lua:211: in function 'cc'
        /usr/local/nginx/ngx_cc-2.1.1/module/invoke.lua:13: in function 'invoker'
        /usr/local/nginx/ngx_cc-2.1.1/ngx_cc.lua:467: in function 'invokes'
        content_by_lua(nginx.conf:67):1: in function <content_by_lua(nginx.conf:67):1>, client: 127.0.0.1, server: localhost, request: "GET /test/hub?getServiceStat HTTP/1.0", host: "127.0.0.1:8011"
    望知悉。

**Comment by aimingoo** [comment]
谢谢stone，第一个问题出在我在online版本中用的是cjson，而不是lib.JSON，所以抓代码出来的时候忽略了这两个接口的差异。第二个问题也与online有关，是因为online版本是多级的，也就是clients不会为nil，而测试的时候因为只有root结点，所以（又因为没有检查ngx_cc:492得到的registed变量是否有效）就出错了。

新版(v2.1.2)修掉了这两个BUG，顺道改了另一个遗漏之处。另外，由于不是所有的nginx都一定编译cjson模块，所以下面贴一段安全代码：

``` lua
-----
-- in head of lib/invoke.lua
-----
local JSON = pcall(require, 'cjson')
if not JSON then
    local JSON2 = require('lib.JSON')
    JSON = {
        encode = function(...) return JSON2:encode(...) end,
        decode = function(...) return JSON2:decode(...) end,
    }
end
```
