### ISSUE TITLE
rotue单词有误？

### ISSUE THREAD

**Issue by stone-wind** [aimingoo/ngx_cc#2]
有两个地方单词应该写错了：rotue -->route
ngx_cc\ngx_cc.lua:10行
    8  -- Usage:
    9  --   ngx_cc = require('ngx_cc')
   10: --   rotue = ngx_cc:new('kada')  -- work with 'kada' channel
   11  --   route.cc('/kada/invoke', 'master')
   12  --     ..

ngx_cc\module\ngx_cc_core.lua:165行
  163   -- fake a requestSelf_BASH(), and direct call route.invoke.setWorker
  164   local function requestSelf_DIRECT(action)
  165:      pcall(route.invoke.setWorker, rotue, channel, { lsof = LSOF_LINES() })
  166   end
  167

**Comment by aimingoo** [comment]
Ok~ Online updated, thanks.
